--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021.12.01 11:45:52
-- Server version: 5.5.5-10.4.6-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

CREATE TABLE projekt.ajanlas (
  ajanlasID INT(11) NOT NULL,
  ajanlasNev VARCHAR(255) DEFAULT NULL,
  ajanlasLeiras VARCHAR(255) DEFAULT NULL,
  ajanlasAr INT(11) NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.fizetes (
  FizetesID INT(11) NOT NULL,
  FizetesTipus VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (FizetesID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.helyszin (
  HelyszinID INT(11) NOT NULL AUTO_INCREMENT,
  HelyszinNev VARCHAR(255) DEFAULT NULL,
  HelyszinTermekek VARCHAR(255) DEFAULT NULL,
  HelyszinAkciok VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (HelyszinID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.promocode (
  PromocodeID INT(11) NOT NULL AUTO_INCREMENT,
  PromocodeSzoveg VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (PromocodeID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.rendeles (
  RendelesID INT(11) NOT NULL,
  RendelesDatum DATE DEFAULT NULL,
  RendelesAzonosito INT(11) NOT NULL,
  PRIMARY KEY (RendelesID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.termekek (
  TermekID INT(11) NOT NULL,
  TermekNev VARCHAR(255) DEFAULT NULL,
  TermekAr INT(11) NOT NULL,
  TermekLeiras VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (TermekID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.user (
  UserID INT(11) NOT NULL,
  UserName VARCHAR(255) DEFAULT NULL,
  UserPassword VARCHAR(255) DEFAULT NULL,
  UserEmail VARCHAR(255) DEFAULT NULL,
  UserNumber INT(11) DEFAULT NULL,
  UserPromo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

CREATE TABLE projekt.utvonal (
  pontokID INT(11) NOT NULL,
  pontokHelyszin VARCHAR(255) DEFAULT NULL,
  pontokTavolsag INT(11) NOT NULL,
  PRIMARY KEY (pontokID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;